chore(ckbtc): update README
dfinity/ic pull request #2956
Opened 2024-12-04 03:07 UTC by ninegua

Add content on how to specify full account when using get_btc_address.
Update the number of confirmations to 6.

2024-12-05 10:27 UTC, letmejustputthishere commented on rs/bitcoin/ckbtc/minter/README.adoc
> +----
lets mention that the args to `update_balance` have to be modified as well to notify the minter and show an example

2024-12-05 10:27 UTC, letmejustputthishere commented on rs/bitcoin/ckbtc/minter/README.adoc
the sequence [diagrams for cketh](https://github.com/dfinity/ic/blob/master/rs/ethereum/cketh/docs/cketh.adoc#deposit-eth-to-cketh) show the arguments for function calls, i think we should do the same here

2025-04-30 14:27 UTC, ninegua commented on rs/bitcoin/ckbtc/minter/README.adoc
> +----
Added

2025-04-30 14:27 UTC, ninegua commented on rs/bitcoin/ckbtc/minter/README.adoc
Good idea! I added arguments to all diagrams in this file, hopefully making them clearer

2025-05-02 09:24 UTC, letmejustputthishere approved these changes

2025-05-02 11:55 UTC, gregorydemay approved these changes
Thanks @ninegua for the improvements!

2025-05-02 11:58 UTC, mducroux requested changes

2025-05-02 11:58 UTC, mducroux commented on rs/bitcoin/ckbtc/minter/README.adoc
> +   │retrieve_btc(adddress,amount)│              │                   │
nit: typo

2025-05-02 12:39 UTC, ninegua commented on rs/bitcoin/ckbtc/minter/README.adoc
> +   │retrieve_btc(adddress,amount)│              │                   │
Thanks! Fixed

2025-05-02 12:46 UTC, mducroux approved these changes
Thanks for the changes! LGTM

2025-05-02 12:54 UTC, merged